/**
 * Build-time template resolution script.
 *
 * Reads the TEMPLATE env var (or parses server/wrangler.toml as fallback)
 * and generates templates/src/_resolved.ts that imports only the selected template.
 * This ensures the Wrangler/esbuild bundle only includes a single template.
 *
 * Template metadata is read from templates.json (single source of truth).
 *
 * Usage:
 *   TEMPLATE=blog pnpm resolve-template
 *   pnpm resolve-template   # reads from server/wrangler.toml
 */

import fs from 'node:fs';
import path from 'node:path';

interface TemplateEntry {
  index: number;
  id: string;
  exportName: string;
  configName: string;
  displayName: string;
  status: string;
}

const ROOT = path.resolve(import.meta.dirname, '../..');
const RESOLVED_PATH = path.resolve(import.meta.dirname, '../src/_resolved.ts');
const WRANGLER_PATH = path.join(ROOT, 'server/wrangler.toml');
const CATALOG_PATH = path.resolve(import.meta.dirname, '../templates.json');

function loadCatalog(): TemplateEntry[] {
  return JSON.parse(fs.readFileSync(CATALOG_PATH, 'utf-8'));
}

function getTemplateName(): string {
  // 1. TEMPLATE env var (highest priority)
  if (process.env.TEMPLATE) {
    return process.env.TEMPLATE;
  }

  // 2. Parse server/wrangler.toml
  try {
    const toml = fs.readFileSync(WRANGLER_PATH, 'utf-8');
    const match = toml.match(/^TEMPLATE\s*=\s*"([^"]+)"/m);
    if (match) return match[1];
  } catch {
    // Fall through to default
  }

  return 'blog';
}

function main() {
  const catalog = loadCatalog();
  const name = getTemplateName();
  const entry = catalog.find(t => t.id === name && t.status === 'shipped');

  if (!entry) {
    const available = catalog.filter(t => t.status === 'shipped').map(t => t.id).join(', ');
    console.error(`Unknown template: "${name}". Available: ${available}`);
    process.exit(1);
  }

  const content = `// AUTO-GENERATED by resolve-template. Do not edit.
// Template: ${entry.id} (#${entry.index})
// Regenerate: TEMPLATE=${entry.id} pnpm resolve-template
export { ${entry.exportName} as resolvedTemplate } from './${entry.id}';
export { ${entry.configName} as resolvedConfig } from './${entry.id}/config';
`;

  // Only write if content changed (avoid unnecessary rebuilds)
  const existing = fs.existsSync(RESOLVED_PATH) ? fs.readFileSync(RESOLVED_PATH, 'utf-8') : '';
  if (existing === content) {
    console.warn(`resolve-template: already resolved to "${name}" (#${entry.index}) — skipped.`);
    return;
  }

  fs.writeFileSync(RESOLVED_PATH, content, 'utf-8');
  console.warn(`resolve-template: resolved to "${name}" (#${entry.index}) → _resolved.ts`);
}

main();
