// AUTO-GENERATED by resolve-template. Do not edit.
// Template: blog (#1)
// Regenerate: TEMPLATE=blog pnpm resolve-template
export { blogTemplate as resolvedTemplate } from './blog';
export { blogConfig as resolvedConfig } from './blog/config';
