export type CatalogStatus = 'shipped' | 'planned' | 'rejected';

export interface CatalogEntry {
  id: string;
  displayName: string;
  tagline: string;
  domain: string;
  contentType: string;
  layout: string;
  status: CatalogStatus;
  /** Why this template exists as separate from others in the same domain */
  differentiators: string[];
  /** If rejected, why (prevents re-proposing the same idea) */
  rejectionReason?: string;
  /** If rejected, which existing template covers this use case */
  coveredBy?: string;
}

export const TEMPLATE_CATALOG: CatalogEntry[] = [
  // --- SHIPPED ---
  {
    id: 'blog',
    displayName: 'Blog / Signals',
    tagline: 'Chronological feed with type badges, reading time, and table of contents',
    domain: 'knowledge',
    contentType: 'articles',
    layout: 'feed',
    status: 'shipped',
    differentiators: ['Timeline-grouped feed', 'Reading time', 'Type-specific guidance patterns', 'Table of contents sidebar'],
  },
  {
    id: 'shop',
    displayName: 'Product Catalog',
    tagline: 'Sidebar categories with grid product cards and search',
    domain: 'commerce',
    contentType: 'listings',
    layout: 'sidebar-grid',
    status: 'shipped',
    differentiators: ['Category sidebar with counts', 'Product grid with hover effects', 'Image placeholder with type initial', 'Excerpt preview on cards'],
  },

  // --- SHIPPED: Tier 1 (unique layouts, broad appeal) ---
  {
    id: 'wiki',
    displayName: 'Wiki / Knowledge Base',
    tagline: 'Tree-structured navigation with interlinked articles',
    domain: 'knowledge',
    contentType: 'articles',
    layout: 'directory',
    status: 'shipped',
    differentiators: ['Tree sidebar (not filter bar)', 'No chronology emphasis', 'Alphabetical/categorical nav', 'Breadcrumb navigation'],
  },
  {
    id: 'portfolio',
    displayName: 'Portfolio / Gallery',
    tagline: 'Visual-dominant grid with large images and minimal text',
    domain: 'creative',
    contentType: 'media',
    layout: 'grid',
    status: 'shipped',
    differentiators: ['Image-first cards (4:3 or square)', 'Horizontal filter chips (no sidebar)', 'Full-width item showcase', 'Masonry-optional layout'],
  },
  {
    id: 'changelog',
    displayName: 'Changelog',
    tagline: 'Version-grouped timeline with semver markers and type badges',
    domain: 'operations',
    contentType: 'records',
    layout: 'timeline',
    status: 'shipped',
    differentiators: ['Version/date markers on timeline', 'Breaking/Feature/Fix badges', 'Horizontal bar cards (not square)', 'Grouped by release version'],
  },
  {
    id: 'magazine',
    displayName: 'Magazine / News',
    tagline: 'Featured hero article with mixed-size card grid below',
    domain: 'media',
    contentType: 'articles',
    layout: 'magazine',
    status: 'shipped',
    differentiators: ['Hero featured article at top', '2-column mixed card sizes', 'Recency emphasis ("2h ago")', 'Editorial section badges'],
  },
  {
    id: 'directory',
    displayName: 'Resource Directory',
    tagline: 'Curated list of external resources with status badges',
    domain: 'community',
    contentType: 'profiles',
    layout: 'directory',
    status: 'shipped',
    differentiators: ['External link cards with domain/favicon', 'Status badges (Active/Archived/New)', 'Alphabetical or categorical grouping', 'No long content — link + short description'],
  },
  {
    id: 'recipes',
    displayName: 'Recipe Collection',
    tagline: 'Grid of recipe cards with prep time, servings, and structured instructions',
    domain: 'personal',
    contentType: 'listings',
    layout: 'grid',
    status: 'shipped',
    differentiators: ['Prep/cook time and servings in card metadata', 'Ingredients list + numbered Instructions in detail', 'Difficulty indicator', 'Grid with food-style gradient placeholders'],
  },

  // --- SHIPPED: Tier 2 ---
  {
    id: 'course',
    displayName: 'Course / Tutorial Series',
    tagline: 'Sequential lessons with chapter navigation and progress',
    domain: 'education',
    contentType: 'articles',
    layout: 'directory',
    status: 'shipped',
    differentiators: ['Ordered lesson sequence (numbered)', 'Next/previous navigation', 'Chapter/module grouping', 'Progress-oriented sidebar'],
  },
  {
    id: 'til',
    displayName: 'Today I Learned',
    tagline: 'Compact micro-entries grouped by day',
    domain: 'knowledge',
    contentType: 'entries',
    layout: 'feed',
    status: 'shipped',
    differentiators: ['Ultra-compact cards', 'No ToC, no long content', 'Date-grouped headers', 'Optimized for daily snippets'],
  },
  {
    id: 'reviews',
    displayName: 'Reviews / Ratings',
    tagline: 'Star/score ratings with pros/cons and comparison tables',
    domain: 'media',
    contentType: 'entries',
    layout: 'feed',
    status: 'shipped',
    differentiators: ['Rating score in card header', 'Pros/cons sections', 'Comparison tables in detail', 'Sort by rating'],
  },
  {
    id: 'case-studies',
    displayName: 'Case Studies',
    tagline: 'Featured case study hero with outcome metrics',
    domain: 'professional',
    contentType: 'articles',
    layout: 'magazine',
    status: 'shipped',
    differentiators: ['Outcome metrics callouts', 'Client attribution', 'Before/after structure', 'Magazine hero + grid'],
  },
  {
    id: 'journal',
    displayName: 'Journal / Diary',
    tagline: 'Date-first entries with daily grouping',
    domain: 'personal',
    contentType: 'entries',
    layout: 'feed',
    status: 'shipped',
    differentiators: ['Large date headers per day', 'No type badges in feed', 'Private-first feel', 'Reflection-oriented actions'],
  },
  {
    id: 'bookshelf',
    displayName: 'Reading List / Bookshelf',
    tagline: 'Book-cover grid with reading status and ratings',
    domain: 'personal',
    contentType: 'listings',
    layout: 'grid',
    status: 'shipped',
    differentiators: ['Portrait aspect-ratio cards (book covers)', 'Read/Reading/Want to Read status', 'Author + page count metadata', 'Shelves as workspaces'],
  },
  {
    id: 'menu',
    displayName: 'Menu / Price List',
    tagline: 'Table layout with section headers and itemized pricing',
    domain: 'commerce',
    contentType: 'listings',
    layout: 'table',
    status: 'shipped',
    differentiators: ['Table with section group headers', 'Short descriptions', 'Pricing column', 'No card grid'],
  },
  {
    id: 'services',
    displayName: 'Service Directory',
    tagline: 'Service tiers with availability status and deliverables',
    domain: 'commerce',
    contentType: 'listings',
    layout: 'directory',
    status: 'shipped',
    differentiators: ['Tier/package display', 'Availability status badges', 'Deliverables list', 'Text-focused, no images'],
  },

  // --- SHIPPED: Tier 3 ---
  {
    id: 'writing',
    displayName: 'Writing / Fiction',
    tagline: 'Distraction-free reading with large typography',
    domain: 'creative',
    contentType: 'articles',
    layout: 'feed',
    status: 'shipped',
    differentiators: ['No sidebar, no badges', 'Large serif typography', 'Drop caps, pull quotes', 'Pure reading experience'],
  },
  {
    id: 'awesome-list',
    displayName: 'Curated List',
    tagline: 'GitHub awesome-list style categorized links',
    domain: 'community',
    contentType: 'entries',
    layout: 'feed',
    status: 'shipped',
    differentiators: ['Section headings with anchor nav', 'Compact link + one-line format', 'No cards, no grid', 'Category-grouped sections'],
  },
  {
    id: 'runbook',
    displayName: 'Runbook / SOP',
    tagline: 'Step-by-step procedures organized by system',
    domain: 'operations',
    contentType: 'articles',
    layout: 'directory',
    status: 'shipped',
    differentiators: ['System/service sidebar', 'Sequential step emphasis', 'Prerequisites section', 'Always-visible ToC'],
  },
  {
    id: 'incidents',
    displayName: 'Incident Log',
    tagline: 'Reverse-chronological timeline with severity coloring',
    domain: 'operations',
    contentType: 'records',
    layout: 'timeline',
    status: 'shipped',
    differentiators: ['Severity coloring (P0-P3)', 'Duration and impact metadata', 'Status badges (Resolved/Investigating)', 'Per-day timeline markers'],
  },
  {
    id: 'podcast',
    displayName: 'Podcast / Episodes',
    tagline: 'Episode feed with numbers, duration, and show notes',
    domain: 'media',
    contentType: 'media',
    layout: 'feed',
    status: 'shipped',
    differentiators: ['Episode number + duration (not reading time)', 'Show notes with timestamps', 'Sequential numbering', 'Audio player placeholder'],
  },
  {
    id: 'flashcards',
    displayName: 'Study Cards',
    tagline: 'Question/answer grid with spaced-repetition actions',
    domain: 'education',
    contentType: 'entries',
    layout: 'grid',
    status: 'shipped',
    differentiators: ['Card-flip UI (front/back)', 'Compact square cards', 'Easy/Medium/Hard/Again actions', 'Spaced repetition focus'],
  },
  {
    id: 'glossary',
    displayName: 'Glossary / Reference',
    tagline: 'Searchable alphabetical table of terms',
    domain: 'knowledge',
    contentType: 'entries',
    layout: 'table',
    status: 'shipped',
    differentiators: ['Alphabetical table layout', 'Term + definition format', 'Search-first UI', 'No feed, no grid'],
  },
  {
    id: 'resume',
    displayName: 'Resume / CV',
    tagline: 'Single-page personal profile with experience timeline',
    domain: 'professional',
    contentType: 'profiles',
    layout: 'dashboard',
    status: 'shipped',
    differentiators: ['Hero bio section', 'Skills grid', 'Experience timeline', 'Not a feed — structured single page'],
  },

  // --- REJECTED (prevents re-proposing) ---
  {
    id: 'tech-blog',
    displayName: 'Tech Blog',
    tagline: '',
    domain: 'knowledge',
    contentType: 'articles',
    layout: 'feed',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Vocabulary swap, not a layout difference',
    coveredBy: 'blog',
  },
  {
    id: 'personal-blog',
    displayName: 'Personal Blog',
    tagline: '',
    domain: 'knowledge',
    contentType: 'articles',
    layout: 'feed',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Vocabulary swap',
    coveredBy: 'blog',
  },
  {
    id: 'travel-blog',
    displayName: 'Travel Blog',
    tagline: '',
    domain: 'personal',
    contentType: 'articles',
    layout: 'feed',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Vocabulary swap',
    coveredBy: 'blog',
  },
  {
    id: 'photo-portfolio',
    displayName: 'Photography Portfolio',
    tagline: '',
    domain: 'creative',
    contentType: 'media',
    layout: 'grid',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Same as portfolio with different seed',
    coveredBy: 'portfolio',
  },
  {
    id: 'design-portfolio',
    displayName: 'Design Portfolio',
    tagline: '',
    domain: 'creative',
    contentType: 'media',
    layout: 'grid',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Same as portfolio with different seed',
    coveredBy: 'portfolio',
  },
  {
    id: 'cookbook',
    displayName: 'Cookbook',
    tagline: '',
    domain: 'personal',
    contentType: 'listings',
    layout: 'grid',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Same as recipes',
    coveredBy: 'recipes',
  },
  {
    id: 'documentation',
    displayName: 'Documentation Site',
    tagline: '',
    domain: 'knowledge',
    contentType: 'articles',
    layout: 'directory',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Same as wiki',
    coveredBy: 'wiki',
  },
  {
    id: 'marketplace',
    displayName: 'Marketplace',
    tagline: '',
    domain: 'commerce',
    contentType: 'listings',
    layout: 'sidebar-grid',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Pignal is single-user; marketplace is multi-seller (hub concept)',
    coveredBy: 'shop',
  },
  {
    id: 'newsletter',
    displayName: 'Newsletter',
    tagline: '',
    domain: 'media',
    contentType: 'articles',
    layout: 'feed',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Same as blog or magazine with email vocabulary',
    coveredBy: 'blog',
  },
  {
    id: 'forum',
    displayName: 'Forum',
    tagline: '',
    domain: 'community',
    contentType: 'entries',
    layout: 'feed',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Pignal is single-user publishing, not multi-user discussion',
  },
  {
    id: 'playbook',
    displayName: 'Playbook',
    tagline: '',
    domain: 'operations',
    contentType: 'articles',
    layout: 'directory',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Same as runbook',
    coveredBy: 'runbook',
  },
  {
    id: 'postmortem',
    displayName: 'Postmortem',
    tagline: '',
    domain: 'operations',
    contentType: 'records',
    layout: 'timeline',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Subset of incidents',
    coveredBy: 'incidents',
  },
  {
    id: 'todo-list',
    displayName: 'To-Do List',
    tagline: '',
    domain: 'personal',
    contentType: 'entries',
    layout: 'kanban',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Wrong tool; Pignal is for published content, not task management',
  },
  {
    id: 'habit-tracker',
    displayName: 'Habit Tracker',
    tagline: '',
    domain: 'personal',
    contentType: 'records',
    layout: 'dashboard',
    status: 'rejected',
    differentiators: [],
    rejectionReason: 'Too interactive for a static content platform',
  },
];

